# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Usar una imagen base de Ubuntu
  config.vm.box = "debian/bullseye64"

  # Configuración de la red
  config.vm.network "public_network"

  # Configuración de puertos
  config.vm.network "forwarded_port", guest: 8080, host: 8080
 
  # Configuración de la carpeta compartida entre el host y la VM si es necesario
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  # Provisionar la máquina para instalar Apache
  config.vm.provision "shell", inline: <<-SHELL
    # Actualizar los paquetes del sistema
    apt-get update -y
    
    # Instalar Apache
    apt-get install apache2 -y
    
    # Habilitar el servicio de Apache para que arranque al inicio
    systemctl enable apache2
    
    # Iniciar el servicio de Apache
    systemctl start apache2

    # Instalacion del OpenJDK
    apt-get install -y openjdk-11-jdk

    # Instalacion del tomcat9
    apt-get install -y tomcat9

    # Configuracion del tomcat9
    groupadd tomcat9
    useradd -s /bin/false -g tomcat9 -d /etc/tomcat9 tomcat9
    # Iniciamos el tomcat9
    systemctl start tomcat9
  SHELL

 
end
