# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Usar una imagen base de Ubuntu
  config.vm.box = "debian/bullseye64"

  # Configuración de la red
  config.vm.network "public_network"

  # Configuración de puertos
  config.vm.network "forwarded_port", guest: 80, host: 8080
 
  # Configuración de la carpeta compartida entre el host y la VM si es necesario
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  # Provisionar la máquina para instalar Apache
  config.vm.provision "shell", inline: <<-SHELL
    # Actualizar los paquetes del sistema
    sudo apt-get update -y
    
    # Instalar Apache
    sudo apt-get install apache2 -y
    
    # Habilitar el servicio de Apache para que arranque al inicio
    sudo systemctl enable apache2
    
    # Iniciar el servicio de Apache
    sudo systemctl start apache2
  SHELL

 
end
