# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Usar una imagen base de Ubuntu
  config.vm.box = "debian/bullseye64"

  # Configuración de la red
  config.vm.network "public_network"

  # Configuración de puertos
  config.vm.network "forwarded_port", guest: 5000, host: 5000
 
  # Configuración de la carpeta compartida entre el host y la VM si es necesario
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  # Provisionar la máquina para instalar Apache
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install -y python3-pip
    pip3 install pipenv
    PATH=$PATH:/home/$USER/.local/bin
    pip3 install python-dotenv
    sudo mkdir -p /var/www/pythonApp
    sudo chown -R $USER:www-data /var/www/pythonApp
    sudo chmod -R 775 /var/www/pythonApp
    sudo cp /vagrant/.env /var/www/pythonApp
  SHELL

 
end
