# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Usar una imagen base de Ubuntu
  config.vm.box = "debian/bullseye64"

  # Configuración de la red
  config.vm.network "public_network"

  # Configuración de puertos
  config.vm.network "forwarded_port", guest: 80, host: 8080
 
  # Configuración de la carpeta compartida entre el host y la VM si es necesario
  config.vm.synced_folder "/practica", "/vagrant", type: "virtualbox"

  # Provisionar la máquina para instalar Apache
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    apt-get update -y
  SHELL

 
end
